/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProsjekterRouteImport } from './routes/prosjekter'
import { Route as PotensielleKunderRouteImport } from './routes/potensielle-kunder'
import { Route as OrdreRouteImport } from './routes/ordre'
import { Route as MobilRouteImport } from './routes/mobil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KunderRouteImport } from './routes/kunder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdmkostRouteImport } from './routes/admkost'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TilbudIndexRouteImport } from './routes/tilbud.index'
import { Route as EndringsmeldingerIndexRouteImport } from './routes/endringsmeldinger.index'
import { Route as TilbudNyRouteImport } from './routes/tilbud.ny'
import { Route as TilbudIdRouteImport } from './routes/tilbud.$id'
import { Route as SignerTokenRouteImport } from './routes/signer.$token'
import { Route as EndringsmeldingerNyRouteImport } from './routes/endringsmeldinger.ny'
import { Route as EndringsmeldingerIdRouteImport } from './routes/endringsmeldinger.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjekterRoute = ProsjekterRouteImport.update({
  id: '/prosjekter',
  path: '/prosjekter',
  getParentRoute: () => rootRouteImport,
} as any)
const PotensielleKunderRoute = PotensielleKunderRouteImport.update({
  id: '/potensielle-kunder',
  path: '/potensielle-kunder',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdreRoute = OrdreRouteImport.update({
  id: '/ordre',
  path: '/ordre',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilRoute = MobilRouteImport.update({
  id: '/mobil',
  path: '/mobil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderRoute = KunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmkostRoute = AdmkostRouteImport.update({
  id: '/admkost',
  path: '/admkost',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TilbudIndexRoute = TilbudIndexRouteImport.update({
  id: '/tilbud/',
  path: '/tilbud/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndringsmeldingerIndexRoute = EndringsmeldingerIndexRouteImport.update({
  id: '/endringsmeldinger/',
  path: '/endringsmeldinger/',
  getParentRoute: () => rootRouteImport,
} as any)
const TilbudNyRoute = TilbudNyRouteImport.update({
  id: '/tilbud/ny',
  path: '/tilbud/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const TilbudIdRoute = TilbudIdRouteImport.update({
  id: '/tilbud/$id',
  path: '/tilbud/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignerTokenRoute = SignerTokenRouteImport.update({
  id: '/signer/$token',
  path: '/signer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EndringsmeldingerNyRoute = EndringsmeldingerNyRouteImport.update({
  id: '/endringsmeldinger/ny',
  path: '/endringsmeldinger/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const EndringsmeldingerIdRoute = EndringsmeldingerIdRouteImport.update({
  id: '/endringsmeldinger/$id',
  path: '/endringsmeldinger/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admkost': typeof AdmkostRoute
  '/dashboard': typeof DashboardRoute
  '/kunder': typeof KunderRoute
  '/login': typeof LoginRoute
  '/mobil': typeof MobilRoute
  '/ordre': typeof OrdreRoute
  '/potensielle-kunder': typeof PotensielleKunderRoute
  '/prosjekter': typeof ProsjekterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/endringsmeldinger/$id': typeof EndringsmeldingerIdRoute
  '/endringsmeldinger/ny': typeof EndringsmeldingerNyRoute
  '/signer/$token': typeof SignerTokenRoute
  '/tilbud/$id': typeof TilbudIdRoute
  '/tilbud/ny': typeof TilbudNyRoute
  '/endringsmeldinger/': typeof EndringsmeldingerIndexRoute
  '/tilbud/': typeof TilbudIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admkost': typeof AdmkostRoute
  '/dashboard': typeof DashboardRoute
  '/kunder': typeof KunderRoute
  '/login': typeof LoginRoute
  '/mobil': typeof MobilRoute
  '/ordre': typeof OrdreRoute
  '/potensielle-kunder': typeof PotensielleKunderRoute
  '/prosjekter': typeof ProsjekterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/endringsmeldinger/$id': typeof EndringsmeldingerIdRoute
  '/endringsmeldinger/ny': typeof EndringsmeldingerNyRoute
  '/signer/$token': typeof SignerTokenRoute
  '/tilbud/$id': typeof TilbudIdRoute
  '/tilbud/ny': typeof TilbudNyRoute
  '/endringsmeldinger': typeof EndringsmeldingerIndexRoute
  '/tilbud': typeof TilbudIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admkost': typeof AdmkostRoute
  '/dashboard': typeof DashboardRoute
  '/kunder': typeof KunderRoute
  '/login': typeof LoginRoute
  '/mobil': typeof MobilRoute
  '/ordre': typeof OrdreRoute
  '/potensielle-kunder': typeof PotensielleKunderRoute
  '/prosjekter': typeof ProsjekterRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/endringsmeldinger/$id': typeof EndringsmeldingerIdRoute
  '/endringsmeldinger/ny': typeof EndringsmeldingerNyRoute
  '/signer/$token': typeof SignerTokenRoute
  '/tilbud/$id': typeof TilbudIdRoute
  '/tilbud/ny': typeof TilbudNyRoute
  '/endringsmeldinger/': typeof EndringsmeldingerIndexRoute
  '/tilbud/': typeof TilbudIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admkost'
    | '/dashboard'
    | '/kunder'
    | '/login'
    | '/mobil'
    | '/ordre'
    | '/potensielle-kunder'
    | '/prosjekter'
    | '/settings'
    | '/status'
    | '/endringsmeldinger/$id'
    | '/endringsmeldinger/ny'
    | '/signer/$token'
    | '/tilbud/$id'
    | '/tilbud/ny'
    | '/endringsmeldinger/'
    | '/tilbud/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admkost'
    | '/dashboard'
    | '/kunder'
    | '/login'
    | '/mobil'
    | '/ordre'
    | '/potensielle-kunder'
    | '/prosjekter'
    | '/settings'
    | '/status'
    | '/endringsmeldinger/$id'
    | '/endringsmeldinger/ny'
    | '/signer/$token'
    | '/tilbud/$id'
    | '/tilbud/ny'
    | '/endringsmeldinger'
    | '/tilbud'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admkost'
    | '/dashboard'
    | '/kunder'
    | '/login'
    | '/mobil'
    | '/ordre'
    | '/potensielle-kunder'
    | '/prosjekter'
    | '/settings'
    | '/status'
    | '/endringsmeldinger/$id'
    | '/endringsmeldinger/ny'
    | '/signer/$token'
    | '/tilbud/$id'
    | '/tilbud/ny'
    | '/endringsmeldinger/'
    | '/tilbud/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdmkostRoute: typeof AdmkostRoute
  DashboardRoute: typeof DashboardRoute
  KunderRoute: typeof KunderRoute
  LoginRoute: typeof LoginRoute
  MobilRoute: typeof MobilRoute
  OrdreRoute: typeof OrdreRoute
  PotensielleKunderRoute: typeof PotensielleKunderRoute
  ProsjekterRoute: typeof ProsjekterRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  EndringsmeldingerIdRoute: typeof EndringsmeldingerIdRoute
  EndringsmeldingerNyRoute: typeof EndringsmeldingerNyRoute
  SignerTokenRoute: typeof SignerTokenRoute
  TilbudIdRoute: typeof TilbudIdRoute
  TilbudNyRoute: typeof TilbudNyRoute
  EndringsmeldingerIndexRoute: typeof EndringsmeldingerIndexRoute
  TilbudIndexRoute: typeof TilbudIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekter': {
      id: '/prosjekter'
      path: '/prosjekter'
      fullPath: '/prosjekter'
      preLoaderRoute: typeof ProsjekterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potensielle-kunder': {
      id: '/potensielle-kunder'
      path: '/potensielle-kunder'
      fullPath: '/potensielle-kunder'
      preLoaderRoute: typeof PotensielleKunderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordre': {
      id: '/ordre'
      path: '/ordre'
      fullPath: '/ordre'
      preLoaderRoute: typeof OrdreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobil': {
      id: '/mobil'
      path: '/mobil'
      fullPath: '/mobil'
      preLoaderRoute: typeof MobilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder': {
      id: '/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof KunderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admkost': {
      id: '/admkost'
      path: '/admkost'
      fullPath: '/admkost'
      preLoaderRoute: typeof AdmkostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilbud/': {
      id: '/tilbud/'
      path: '/tilbud'
      fullPath: '/tilbud/'
      preLoaderRoute: typeof TilbudIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endringsmeldinger/': {
      id: '/endringsmeldinger/'
      path: '/endringsmeldinger'
      fullPath: '/endringsmeldinger/'
      preLoaderRoute: typeof EndringsmeldingerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilbud/ny': {
      id: '/tilbud/ny'
      path: '/tilbud/ny'
      fullPath: '/tilbud/ny'
      preLoaderRoute: typeof TilbudNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilbud/$id': {
      id: '/tilbud/$id'
      path: '/tilbud/$id'
      fullPath: '/tilbud/$id'
      preLoaderRoute: typeof TilbudIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signer/$token': {
      id: '/signer/$token'
      path: '/signer/$token'
      fullPath: '/signer/$token'
      preLoaderRoute: typeof SignerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endringsmeldinger/ny': {
      id: '/endringsmeldinger/ny'
      path: '/endringsmeldinger/ny'
      fullPath: '/endringsmeldinger/ny'
      preLoaderRoute: typeof EndringsmeldingerNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endringsmeldinger/$id': {
      id: '/endringsmeldinger/$id'
      path: '/endringsmeldinger/$id'
      fullPath: '/endringsmeldinger/$id'
      preLoaderRoute: typeof EndringsmeldingerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdmkostRoute: AdmkostRoute,
  DashboardRoute: DashboardRoute,
  KunderRoute: KunderRoute,
  LoginRoute: LoginRoute,
  MobilRoute: MobilRoute,
  OrdreRoute: OrdreRoute,
  PotensielleKunderRoute: PotensielleKunderRoute,
  ProsjekterRoute: ProsjekterRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  EndringsmeldingerIdRoute: EndringsmeldingerIdRoute,
  EndringsmeldingerNyRoute: EndringsmeldingerNyRoute,
  SignerTokenRoute: SignerTokenRoute,
  TilbudIdRoute: TilbudIdRoute,
  TilbudNyRoute: TilbudNyRoute,
  EndringsmeldingerIndexRoute: EndringsmeldingerIndexRoute,
  TilbudIndexRoute: TilbudIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
